# Dependabot will run on day 6 of each month at 02:59 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "59 2 6 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
