version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: Europe/Berlin
      cronjob: '40 3 22 * *'
    open-pull-requests-limit: 20
    versioning-strategy: increase

    # the vis-2 widget set has its own dependencies (react, vite, module federation)
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
  - package-ecosystem: npm
    directory: '/src-widgets'
    schedule:
      interval: 'cron'
      timezone: Europe/Berlin
      cronjob: '40 3 22 * *'
    open-pull-requests-limit: 20
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: Europe/Berlin
      cronjob: '40 3 22 * *'
    open-pull-requests-limit: 15
